apiVersion: v1
kind: ReplicationController
metadata:
  name: java-rc
spec:
  replicas: 2
  selector:
    app: java
  template:
    metadata:
      name: java
      labels:
        app: java
    spec:
      containers:
      - name: tomcatlatest
        image: allurimadhu1993/kubedeploy
        ports:
        - containerPort: 8080
