apiVersion: v1
kind: ReplicationController
metadata:
  name: tom-rc
spec:
  replicas: 2
  selector:
    app: tom
  template:
    metadata:
      name: tom
      labels:
        app: tom
    spec:
      containers:
      - name: tom
        image: allurimadhu1993/kubedeploy
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tom
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tom
