apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-rc
spec:
  replicas: 2
  selector:
    matchLabels: 
     app: tom
  template:
    metadata:
      name: mypod
      labels:
        app: tom
    spec:
      containers: 
        - name: tomcat
          image: allurimadhu1993/kubedeploy
          ports:
           - name: tom-port
             containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tom
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tom
